# Site
name: "Aakash"
title: "Aakash"
description: "Web Developer | Electrical Engineer | Deep Learning Enthusiast | Multi-Lingual"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
include: ["_pages"]
permalink: /blog/:title/
email: wowthemesnet@gmail.com

# Authors
authors:
  aakash:
    name: Aakash
    display_name: Aakash
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://prepsera.wordpress.com/
    description: "Blogger by day, coder by night. Perfectionist with an insatiable thirst for knowledge."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
